USE oa_system;
SET NAMES utf8mb4;

-- 依据《国务院办公厅关于2026年部分节假日安排的通知》
-- 国办发明电〔2025〕7号：
-- https://www.gov.cn/zhengce/zhengceku/202511/content_7047091.htm
-- 可重复执行；企业可在前端继续覆盖个别日期。
INSERT INTO attendance_calendar_day
    (work_date, day_type, holiday_name, created_at, updated_at)
VALUES
    ('2026-01-01', 'HOLIDAY', '元旦', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-01-02', 'HOLIDAY', '元旦', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-01-03', 'HOLIDAY', '元旦', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-01-04', 'WORKDAY', '元旦调休上班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-14', 'WORKDAY', '春节调休上班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-15', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-16', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-17', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-18', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-19', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-20', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-21', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-22', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-23', 'HOLIDAY', '春节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-02-28', 'WORKDAY', '春节调休上班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-04-04', 'HOLIDAY', '清明节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-04-05', 'HOLIDAY', '清明节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-04-06', 'HOLIDAY', '清明节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-05-01', 'HOLIDAY', '劳动节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-05-02', 'HOLIDAY', '劳动节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-05-03', 'HOLIDAY', '劳动节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-05-04', 'HOLIDAY', '劳动节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-05-05', 'HOLIDAY', '劳动节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-05-09', 'WORKDAY', '劳动节调休上班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-06-19', 'HOLIDAY', '端午节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-06-20', 'HOLIDAY', '端午节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-06-21', 'HOLIDAY', '端午节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-09-20', 'WORKDAY', '国庆节调休上班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-09-25', 'HOLIDAY', '中秋节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-09-26', 'HOLIDAY', '中秋节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-09-27', 'HOLIDAY', '中秋节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-01', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-02', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-03', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-04', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-05', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-06', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-07', 'HOLIDAY', '国庆节', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('2026-10-10', 'WORKDAY', '国庆节调休上班', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    day_type = VALUES(day_type),
    holiday_name = VALUES(holiday_name),
    updated_at = CURRENT_TIMESTAMP;
